// src/solid/components/Panel.tsx
import { buildCopyInstruction } from '../../copy-instruction';
import { batch, createSignal, createEffect, on, onMount, onCleanup, type JSX } from 'solid-js';
import { animate } from 'motion';
import { ICON_CLIPBOARD_PLAIN, ICON_CHECK } from '../../icons';
import { DialStore } from '../../store/DialStore';
import type { PanelConfig, DialValue } from '../../store/DialStore';
import type { AnimationHandle } from '../primitives';
import { Folder } from './Folder';
import { RootPanel } from './RootPanel';
import { ControlRenderer } from './ControlRenderer';
import { PresetManager } from './PresetManager';

interface PanelProps {
  panel: PanelConfig;
  defaultOpen?: boolean;
  inline?: boolean;
  onOpenChange?: (open: boolean) => void;
  variant?: 'root' | 'section';
  toolbarExtra?: JSX.Element;
}

export function Panel(props: PanelProps) {
  const [copied, setCopied] = createSignal(false);
  let copyTimeout: ReturnType<typeof setTimeout> | undefined;
  const [values, setValues] = createSignal<Record<string, DialValue>>(
    DialStore.getValues(props.panel.id)
  );
  const [presets, setPresets] = createSignal(DialStore.getPresets(props.panel.id));
  const [activePresetId, setActivePresetId] = createSignal(DialStore.getActivePresetId(props.panel.id));
  // The store owns open/collapsed state so it can be driven programmatically.
  const [storeOpen, setStoreOpen] = createSignal(DialStore.getPanelOpen(props.panel.id));
  const isOpen = () => storeOpen() ?? props.defaultOpen ?? true;
  let copyButtonRef!: HTMLButtonElement;
  let copyClipboardIconRef!: HTMLSpanElement;
  let copyCheckIconRef!: HTMLSpanElement;
  let copyTapAnim: AnimationHandle | null = null;
  let copyClipboardAnim: AnimationHandle | null = null;
  let copyCheckAnim: AnimationHandle | null = null;

  const tapTransition = { type: 'spring' as const, visualDuration: 0.15, bounce: 0.3 };

  onMount(() => {
    const unsub = DialStore.subscribe(props.panel.id, () => {
      batch(() => {
        setValues(DialStore.getValues(props.panel.id));
        setPresets(DialStore.getPresets(props.panel.id));
        setActivePresetId(DialStore.getActivePresetId(props.panel.id));
        setStoreOpen(DialStore.getPanelOpen(props.panel.id));
      });
    });
    DialStore.initPanelOpen(props.panel.id, props.defaultOpen ?? true);
    onCleanup(unsub);
  });

  const handleCopy = async () => {
    const instruction = buildCopyInstruction('createDialKit', props.panel.name, values());
    try { await navigator.clipboard.writeText(instruction); }
    catch { return; }
    setCopied(true);
    clearTimeout(copyTimeout);
    copyTimeout = setTimeout(() => setCopied(false), 1500);
  };

  // Icons render with their resting styles inline; only animate on changes.
  createEffect(on(copied, (isCopied) => {
    if (!copyClipboardIconRef || !copyCheckIconRef) return;

    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();

    const transition = { type: 'spring' as const, visualDuration: 0.3, bounce: 0.2 };
    copyClipboardAnim = animate(copyClipboardIconRef, {
      opacity: isCopied ? 0 : 1,
      scale: isCopied ? 0.5 : 1,
      filter: isCopied ? 'blur(4px)' : 'blur(0px)',
    }, transition);
    copyCheckAnim = animate(copyCheckIconRef, {
      opacity: isCopied ? 1 : 0,
      scale: isCopied ? 1 : 0.5,
      filter: isCopied ? 'blur(0px)' : 'blur(4px)',
    }, transition);
  }, { defer: true }));

  onCleanup(() => {
    clearTimeout(copyTimeout);
    copyTapAnim?.stop();
    copyClipboardAnim?.stop();
    copyCheckAnim?.stop();
  });

  const handleCopyTapStart = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 0.95 }, tapTransition);
  };

  const handleCopyTapEnd = () => {
    if (!copyButtonRef) return;
    copyTapAnim?.stop();
    copyTapAnim = animate(copyButtonRef, { scale: 1 }, tapTransition);
  };

  const handleOpenChange = (open: boolean) => {
    DialStore.setPanelOpen(props.panel.id, open);
    props.onOpenChange?.(open);
  };

  const toolbar = (
    <>
      <PresetManager
        panelId={props.panel.id}
        presets={presets()}
        activePresetId={activePresetId()}
      />

      <button
        ref={copyButtonRef}
        class="dialkit-toolbar-add dialkit-toolbar-primary"
        onClick={handleCopy}
        onPointerDown={handleCopyTapStart}
        onPointerUp={handleCopyTapEnd}
        onPointerCancel={handleCopyTapEnd}
        onPointerLeave={handleCopyTapEnd}
        title="Copy parameters" aria-label="Copy parameters"
      >
        <span class="dialkit-toolbar-copy-icon-wrap">
          <span
            ref={copyClipboardIconRef}
            class="dialkit-toolbar-copy-icon"
            style={{ opacity: 1, transform: 'scale(1)', filter: 'blur(0px)', 'transform-origin': '50% 50%' }}
          >
            <svg viewBox="0 0 24 24" fill="none" width="16" height="16">
              <path d={ICON_CLIPBOARD_PLAIN.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round" />
              <path d={ICON_CLIPBOARD_PLAIN.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" />
            </svg>
          </span>
          <span
            ref={copyCheckIconRef}
            class="dialkit-toolbar-copy-icon"
            style={{ opacity: 0, transform: 'scale(0.5)', filter: 'blur(4px)', 'transform-origin': '50% 50%' }}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" width="16" height="16">
              <path d={ICON_CHECK} />
            </svg>
          </span>
        </span>
      </button>

      {props.toolbarExtra}

    </>
  );

  if (props.variant === 'section') {
    return (
      <Folder title={props.panel.name} open={isOpen()} onOpenChange={handleOpenChange}>
        <div class="dialkit-panel-section-toolbar" onClick={(e) => e.stopPropagation()}>
          {toolbar}
        </div>
        <ControlRenderer panelId={props.panel.id} controls={props.panel.controls} values={values()} />
      </Folder>
    );
  }

  return (
    <div class="dialkit-panel-wrapper">
      <RootPanel title={props.panel.name} open={isOpen()} inline={props.inline ?? false} onOpenChange={handleOpenChange} toolbar={toolbar}>
        <ControlRenderer panelId={props.panel.id} controls={props.panel.controls} values={values()} />
      </RootPanel>
    </div>
  );
}

// src/svelte/components/Panel.svelte
<script lang="ts">
  import { buildCopyInstruction } from '../../copy-instruction';
  import { Spring } from 'svelte/motion';
  import type { Snippet } from 'svelte';
  import { DialStore } from 'dialkit/store';
  import type { DialValue, PanelConfig, Preset } from 'dialkit/store';
  import Folder from './Folder.svelte';
  import PresetManager from './PresetManager.svelte';
  import ControlRenderer from './ControlRenderer.svelte';
  import { ICON_CLIPBOARD_PLAIN, ICON_CHECK } from '../../icons';

  let { panel, defaultOpen = true, inline = false, onOpenChange, variant = 'root', toolbarExtra } = $props<{
    panel: PanelConfig;
    defaultOpen?: boolean;
    inline?: boolean;
    onOpenChange?: (open: boolean) => void;
    variant?: 'root' | 'section';
    toolbarExtra?: Snippet;
  }>();

  let copied = $state(false);
  // The store owns open/collapsed state so it can be driven programmatically.
  let storeOpen = $state<boolean | undefined>(DialStore.getPanelOpen(panel.id));
  const isOpen = $derived(storeOpen ?? defaultOpen);
  let values = $state<Record<string, DialValue>>(DialStore.getValues(panel.id));
  let presets = $state<Preset[]>(DialStore.getPresets(panel.id));
  let activePresetId = $state<string | null>(DialStore.getActivePresetId(panel.id));

  const copyScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardOpacity = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardScale = new Spring(1, { stiffness: 0.2, damping: 0.6 });
  const checkOpacity = new Spring(0, { stiffness: 0.25, damping: 0.7 });
  const checkScale = new Spring(0.5, { stiffness: 0.2, damping: 0.6 });

  let copyTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    const unsub = DialStore.subscribe(panel.id, () => {
      values = DialStore.getValues(panel.id);
      presets = DialStore.getPresets(panel.id);
      activePresetId = DialStore.getActivePresetId(panel.id);
      storeOpen = DialStore.getPanelOpen(panel.id);
    });
    DialStore.initPanelOpen(panel.id, defaultOpen);

    return () => {
      unsub();
      if (copyTimeout) clearTimeout(copyTimeout);
    };
  });

  $effect(() => {
    if (copied) {
      clipboardOpacity.set(0);
      clipboardScale.set(0.5);
      checkOpacity.set(1);
      checkScale.set(1);
      return;
    }

    clipboardOpacity.set(1);
    clipboardScale.set(1);
    checkOpacity.set(0);
    checkScale.set(0.5);
  });

  const handleCopy = async () => {
    const instruction = buildCopyInstruction('createDialKit', panel.name, values);

    try { await navigator.clipboard.writeText(instruction); }
    catch { return; }
    copied = true;

    if (copyTimeout) clearTimeout(copyTimeout);
    copyTimeout = setTimeout(() => {
      copied = false;
    }, 1500);
  };

  const handleOpenChange = (open: boolean) => {
    DialStore.setPanelOpen(panel.id, open);
    onOpenChange?.(open);
  };
</script>

{#snippet panelToolbar()}
  <PresetManager panelId={panel.id} {presets} {activePresetId} />

  <button
    class="dialkit-toolbar-add dialkit-toolbar-primary"
    onclick={handleCopy}
    onpointerdown={() => copyScale.set(0.95)}
    onpointerup={() => copyScale.set(1)}
    onpointercancel={() => copyScale.set(1)}
    onpointerleave={() => copyScale.set(1)}
    title="Copy parameters" aria-label="Copy parameters"
    style:transform={`scale(${copyScale.current})`}
  >
    <span class="dialkit-toolbar-copy-icon-wrap">
      <svg
        class="dialkit-toolbar-copy-icon"
        viewBox="0 0 24 24"
        fill="none"
        style:opacity={clipboardOpacity.current}
        style:transform={`scale(${clipboardScale.current})`}
        style:filter={`blur(${(1 - clipboardOpacity.current) * 4}px)`}
      >
        <path d={ICON_CLIPBOARD_PLAIN.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>
        <path d={ICON_CLIPBOARD_PLAIN.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>

      <svg
        class="dialkit-toolbar-copy-icon"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        style:opacity={checkOpacity.current}
        style:transform={`scale(${checkScale.current})`}
        style:filter={`blur(${(1 - checkOpacity.current) * 4}px)`}
      >
        <path d={ICON_CHECK} />
      </svg>
    </span>
  </button>

  {#if toolbarExtra}
    {@render toolbarExtra()}
  {/if}
{/snippet}

{#snippet panelControls()}
  {#each panel.controls as control (control.path)}
    <ControlRenderer panelId={panel.id} {control} {values} />
  {/each}
{/snippet}

{#if variant === 'section'}
  <Folder title={panel.name} open={isOpen} onOpenChange={handleOpenChange}>
    <div class="dialkit-panel-section-toolbar" onclick={(e) => e.stopPropagation()}>
      {@render panelToolbar()}
    </div>
    {@render panelControls()}
  </Folder>
{:else}
  <div class="dialkit-panel-wrapper">
    <Folder title={panel.name} open={isOpen} isRoot={true} {inline} onOpenChange={handleOpenChange}>
      {#snippet toolbar()}
        {@render panelToolbar()}
      {/snippet}

      {@render panelControls()}
    </Folder>
  </div>
{/if}
