// src/components/Panel.tsx
import { useCallback, useEffect, useRef, useState, useSyncExternalStore } from 'react';
import type { ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { DialStore, PanelConfig } from '../store/DialStore';
import { buildCopyInstruction } from '../copy-instruction';
import { ICON_CLIPBOARD_PLAIN, ICON_CHECK, ICON_PLUS } from '../icons';
import { ControlRenderer } from './ControlRenderer';
import { Folder } from './Folder';
import { PresetManager } from './PresetManager';

interface PanelProps {
  panel: PanelConfig;
  defaultOpen?: boolean;
  inline?: boolean;
  onOpenChange?: (open: boolean) => void;
  variant?: 'root' | 'section';
  toolbarExtra?: ReactNode;
}

export function Panel({ panel, defaultOpen = true, inline = false, onOpenChange, variant = 'root', toolbarExtra }: PanelProps) {
  const [copied, setCopied] = useState(false);
  const copyTimeout = useRef<ReturnType<typeof setTimeout>>();
  useEffect(() => () => clearTimeout(copyTimeout.current), []);
  const subscribe = useCallback(
    (callback: () => void) => DialStore.subscribe(panel.id, callback),
    [panel.id]
  );
  const getSnapshot = useCallback(
    () => DialStore.getValues(panel.id),
    [panel.id]
  );
  const getOpenSnapshot = useCallback(
    () => DialStore.getPanelOpen(panel.id),
    [panel.id]
  );

  // Subscribe to panel value changes
  const values = useSyncExternalStore(subscribe, getSnapshot, getSnapshot);

  // The store owns open/collapsed state so it can be driven programmatically.
  const storeOpen = useSyncExternalStore(subscribe, getOpenSnapshot, getOpenSnapshot);
  const isOpen = storeOpen ?? defaultOpen;

  useEffect(() => {
    DialStore.initPanelOpen(panel.id, defaultOpen);
  }, [panel.id, defaultOpen]);

  const presets = DialStore.getPresets(panel.id);
  const activePresetId = DialStore.getActivePresetId(panel.id);

  const handleAddPreset = () => {
    const nextNum = presets.length + 2;
    DialStore.savePreset(panel.id, `Version ${nextNum}`);
  };

  const handleCopy = async () => {
    try { await navigator.clipboard.writeText(buildCopyInstruction('useDialKit', panel.name, values)); }
    catch { return; }
    setCopied(true);
    clearTimeout(copyTimeout.current);
    copyTimeout.current = setTimeout(() => setCopied(false), 1500);
  };

  const handleOpenChange = useCallback((open: boolean) => {
    DialStore.setPanelOpen(panel.id, open);
    onOpenChange?.(open);
  }, [onOpenChange, panel.id]);

  const renderControls = () => (
    <ControlRenderer panelId={panel.id} controls={panel.controls} values={values} />
  );

  const iconTransition = { type: 'spring' as const, visualDuration: 0.4, bounce: 0.1 };

  const toolbar = (
    <>
      <motion.button
        className="dialkit-toolbar-add"
        onClick={handleAddPreset}
        title="Add preset"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
          {ICON_PLUS.map((d, i) => (
            <path key={i} d={d} />
          ))}
        </svg>
      </motion.button>

      <PresetManager
        panelId={panel.id}
        presets={presets}
        activePresetId={activePresetId}
        onAdd={handleAddPreset}
      />

      <motion.button
        className="dialkit-toolbar-add dialkit-toolbar-primary"
        onClick={handleCopy}
        title="Copy parameters"
        whileTap={{ scale: 0.9 }}
        transition={{ type: 'spring', visualDuration: 0.15, bounce: 0.3 }}
      >
        <span style={{ position: 'relative', width: 16, height: 16 }}>
          <AnimatePresence initial={false} mode="wait">
            {copied ? (
              <motion.svg
                key="check"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                style={{ position: 'absolute', inset: 0, width: 16, height: 16, color: 'inherit' }}
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                transition={{ duration: 0.08 }}
              >
                <path d={ICON_CHECK} />
              </motion.svg>
            ) : (
              <motion.svg
                key="clipboard"
                viewBox="0 0 24 24"
                fill="none"
                style={{ position: 'absolute', inset: 0, width: 16, height: 16, color: 'inherit' }}
                initial={{ scale: 0.8, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                exit={{ scale: 0.8, opacity: 0 }}
                transition={{ duration: 0.08 }}
              >
                <path d={ICON_CLIPBOARD_PLAIN.board} stroke="currentColor" strokeWidth="2" strokeLinejoin="round"/>
                <path d={ICON_CLIPBOARD_PLAIN.body} stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
              </motion.svg>
            )}
          </AnimatePresence>
        </span>
      </motion.button>

      {toolbarExtra}
    </>
  );

  if (variant === 'section') {
    return (
      <Folder title={panel.name} open={isOpen} onOpenChange={handleOpenChange}>
        <div className="dialkit-panel-section-toolbar" onClick={(e) => e.stopPropagation()}>
          {toolbar}
        </div>
        {renderControls()}
      </Folder>
    );
  }

  return (
    <div className="dialkit-panel-wrapper">
      <Folder title={panel.name} open={isOpen} isRoot={true} inline={inline} onOpenChange={handleOpenChange} toolbar={toolbar}>
        {renderControls()}
      </Folder>
    </div>
  );
}

// src/svelte/components/Panel.svelte
<script lang="ts">
  import { buildCopyInstruction } from '../../copy-instruction';
  import { Spring } from 'svelte/motion';
  import type { Snippet } from 'svelte';
  import { DialStore } from 'dialkit/store';
  import type { DialValue, PanelConfig, Preset } from 'dialkit/store';
  import Folder from './Folder.svelte';
  import PresetManager from './PresetManager.svelte';
  import ControlRenderer from './ControlRenderer.svelte';
  import { ICON_CLIPBOARD_PLAIN, ICON_CHECK, ICON_PLUS } from '../../icons';

  let { panel, defaultOpen = true, inline = false, onOpenChange, variant = 'root', toolbarExtra } = $props<{
    panel: PanelConfig;
    defaultOpen?: boolean;
    inline?: boolean;
    onOpenChange?: (open: boolean) => void;
    variant?: 'root' | 'section';
    toolbarExtra?: Snippet;
  }>();


  let copied = $state(false);
  // The store owns open/collapsed state so it can be driven programmatically.
  let storeOpen = $state<boolean | undefined>(DialStore.getPanelOpen(panel.id));
  const isOpen = $derived(storeOpen ?? defaultOpen);
  let values = $state<Record<string, DialValue>>(DialStore.getValues(panel.id));
  let presets = $state<Preset[]>(DialStore.getPresets(panel.id));
  let activePresetId = $state<string | null>(DialStore.getActivePresetId(panel.id));

  const addScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const copyScale = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardOpacity = new Spring(1, { stiffness: 0.25, damping: 0.7 });
  const clipboardScale = new Spring(1, { stiffness: 0.2, damping: 0.6 });
  const checkOpacity = new Spring(0, { stiffness: 0.25, damping: 0.7 });
  const checkScale = new Spring(0.5, { stiffness: 0.2, damping: 0.6 });

  let copyTimeout: ReturnType<typeof setTimeout> | undefined;

  $effect(() => {
    const unsub = DialStore.subscribe(panel.id, () => {
      values = DialStore.getValues(panel.id);
      presets = DialStore.getPresets(panel.id);
      activePresetId = DialStore.getActivePresetId(panel.id);
      storeOpen = DialStore.getPanelOpen(panel.id);
    });
    DialStore.initPanelOpen(panel.id, defaultOpen);

    return () => {
      unsub();
      if (copyTimeout) clearTimeout(copyTimeout);
    };
  });

  $effect(() => {
    if (copied) {
      clipboardOpacity.set(0);
      clipboardScale.set(0.5);
      checkOpacity.set(1);
      checkScale.set(1);
      return;
    }

    clipboardOpacity.set(1);
    clipboardScale.set(1);
    checkOpacity.set(0);
    checkScale.set(0.5);
  });

  const handleAddPreset = () => {
    const nextNum = presets.length + 2;
    DialStore.savePreset(panel.id, `Version ${nextNum}`);
  };

  const handleCopy = async () => {
    const instruction = buildCopyInstruction('createDialKit', panel.name, values);

    try { await navigator.clipboard.writeText(instruction); }
    catch { return; }
    copied = true;

    if (copyTimeout) clearTimeout(copyTimeout);
    copyTimeout = setTimeout(() => {
      copied = false;
    }, 1500);
  };

  const handleOpenChange = (open: boolean) => {
    DialStore.setPanelOpen(panel.id, open);
    onOpenChange?.(open);
  };
</script>

{#snippet panelToolbar()}
  <button
    class="dialkit-toolbar-add"
    onclick={handleAddPreset}
    onpointerdown={() => addScale.set(0.9)}
    onpointerup={() => addScale.set(1)}
    onpointercancel={() => addScale.set(1)}
    onpointerleave={() => addScale.set(1)}
    title="Add preset"
    style:transform={`scale(${addScale.current})`}
  >
    <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
      <path d={ICON_PLUS[0]} />
    </svg>
  </button>

  <PresetManager panelId={panel.id} {presets} {activePresetId} />

  <button
    class="dialkit-toolbar-copy dialkit-toolbar-primary"
    onclick={handleCopy}
    onpointerdown={() => copyScale.set(0.95)}
    onpointerup={() => copyScale.set(1)}
    onpointercancel={() => copyScale.set(1)}
    onpointerleave={() => copyScale.set(1)}
    title="Copy parameters"
    style:transform={`scale(${copyScale.current})`}
  >
    <span class="dialkit-toolbar-copy-icon-wrap">
      <svg
        class="dialkit-toolbar-copy-icon"
        viewBox="0 0 24 24"
        fill="none"
        style:opacity={clipboardOpacity.current}
        style:transform={`scale(${clipboardScale.current})`}
        style:filter={`blur(${(1 - clipboardOpacity.current) * 4}px)`}
      >
        <path d={ICON_CLIPBOARD_PLAIN.board} stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>
        <path d={ICON_CLIPBOARD_PLAIN.body} stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
      </svg>

      <svg
        class="dialkit-toolbar-copy-icon"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
        stroke-linecap="round"
        stroke-linejoin="round"
        style:opacity={checkOpacity.current}
        style:transform={`scale(${checkScale.current})`}
        style:filter={`blur(${(1 - checkOpacity.current) * 4}px)`}
      >
        <path d={ICON_CHECK} />
      </svg>
    </span>
    Copy
  </button>

  {#if toolbarExtra}
    {@render toolbarExtra()}
  {/if}
{/snippet}

{#snippet panelControls()}
  {#each panel.controls as control (control.path)}
    <ControlRenderer panelId={panel.id} {control} {values} />
  {/each}
{/snippet}

{#if variant === 'section'}
  <Folder title={panel.name} open={isOpen} onOpenChange={handleOpenChange}>
    <div class="dialkit-panel-section-toolbar" onclick={(e) => e.stopPropagation()}>
      {@render panelToolbar()}
    </div>
    {@render panelControls()}
  </Folder>
{:else}
  <div class="dialkit-panel-wrapper">
    <Folder title={panel.name} open={isOpen} isRoot={true} {inline} onOpenChange={handleOpenChange}>
      {#snippet toolbar()}
        {@render panelToolbar()}
      {/snippet}

      {@render panelControls()}
    </Folder>
  </div>
{/if}
